[project]
name = "mojal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "modal>=1.0.5",
    "modular>=25.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]
