[workspace]
authors = ["zsiegel92 <zsiegel92@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo_app"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025070315,<26"
